export const defaultPreferences = {
    ai_version: "4.x",
    enhance_type: "neutral",
    vertical_correction: true,
    sky_replacement: true,
    cloud_type: "LOW_CLOUD",
    contrast_boost: "NONE",
    lens_correction: true,
    privacy: false,
    hdr: false,
    single_bracket: true,
    threesixty: false,
    window_pull: true,
    saturation_level: "NONE",
    brightness_boost: "NONE",
    sharpen_level: "NONE",
    denoise_level: "NONE",
    clarity_level: "NONE",
};
